"""PDF export — HTML to PDF via WeasyPrint."""

from __future__ import annotations

import asyncio
import concurrent.futures
import logging
from pathlib import Path

from artifactor.export.html import markdown_to_html
from artifactor.export.mermaid_prerender import (
    prerender_mermaid_blocks,
)
from artifactor.outputs.base import SectionOutput

logger = logging.getLogger(__name__)

# ── Branded PDF stylesheet (BRAND_GUIDELINES.md tokens) ────

PDF_STYLESHEET = """
@page {
  size: Letter;
  margin: 0.75in 0.75in 1in 0.75in;
  @top-right {
    content: "Artifactor";
    font-family: system-ui, sans-serif;
    font-size: 8pt;
    color: #6B7280;
  }
  @bottom-center {
    content: counter(page);
    font-family: system-ui, sans-serif;
    font-size: 8pt;
    color: #6B7280;
  }
}

@page :first {
  @top-right { content: ""; }
  @bottom-center { content: ""; }
}

body {
  font-family: system-ui, sans-serif;
  font-size: 10pt;
  line-height: 1.6;
  color: #1F2937;
  max-width: none;
  margin: 0;
  padding: 0;
}

h1 { color: #3730A3; font-size: 18pt; margin-top: 1.5em; }
h2 { color: #3730A3; font-size: 14pt; border-bottom: 1px solid #E5E7EB;
     padding-bottom: 0.3em; }
h3 { color: #4338CA; font-size: 12pt; }

code {
  font-family: 'JetBrains Mono', ui-monospace, monospace;
  font-size: 8.5pt;
  background: #F3F4F6;
  padding: 0.15em 0.3em;
  border-radius: 3px;
}

pre {
  font-family: 'JetBrains Mono', ui-monospace, monospace;
  font-size: 8pt;
  background: #F8F9FA;
  border: 1px solid #E5E7EB;
  border-left: 3px solid #3730A3;
  padding: 0.75em 1em;
  border-radius: 4px;
  white-space: pre-wrap;
  page-break-inside: avoid;
}

table {
  border-collapse: collapse;
  width: 100%;
  margin: 1em 0;
  font-size: 9pt;
  page-break-inside: avoid;
}
th { background: #3730A3; color: white; padding: 0.5em; text-align: left; }
td { border: 1px solid #E5E7EB; padding: 0.5em; }
tr:nth-child(even) { background: #F9FAFB; }

section { page-break-before: always; }
section:first-of-type { page-break-before: avoid; }

.citation {
  border-left: 3px solid #3730A3;
  background: #EEF2FF;
  padding: 0.5em 1em;
  font-family: 'JetBrains Mono', ui-monospace, monospace;
  font-size: 8pt;
  margin: 0.5em 0;
  page-break-inside: avoid;
}

#toc a { color: #3730A3; text-decoration: none; }
#toc a::after { content: leader('.') target-counter(attr(href), page); }

.cover-page {
  text-align: center;
  padding-top: 3in;
  page-break-after: always;
}
.cover-page h1 { font-size: 28pt; color: #3730A3; border: none; }
.cover-page .subtitle { font-size: 14pt; color: #6B7280; margin-top: 0.5em; }
.cover-page .meta { font-size: 10pt; color: #9CA3AF; margin-top: 2em; }
"""


def _build_pdf_html(
    sections: list[SectionOutput],
    project_id: str,
) -> str:
    """Build a PDF-optimized HTML document with cover and TOC."""
    from datetime import UTC, datetime

    parts: list[str] = []

    parts.append("<!DOCTYPE html><html lang='en'><head>")
    parts.append("<meta charset='utf-8'>")
    parts.append(f"<title>Artifactor — {project_id}</title>")
    parts.append(f"<style>{PDF_STYLESHEET}</style>")
    parts.append("</head><body>")

    # Cover page
    parts.append('<div class="cover-page">')
    parts.append(f"<h1>{project_id}</h1>")
    parts.append(
        '<div class="subtitle">Code Intelligence Report</div>'
    )
    date_str = datetime.now(UTC).strftime("%Y-%m-%d")
    parts.append(
        f'<div class="meta">'
        f"Generated by Artifactor — {date_str}"
        f"</div>"
    )
    parts.append("</div>")

    # Table of Contents
    parts.append('<div id="toc">')
    parts.append("<h2>Table of Contents</h2>")
    for section in sections:
        anchor = section.section_name.replace("_", "-")
        parts.append(
            f'<p><a href="#{anchor}">{section.title}</a></p>'
        )
    parts.append("</div>")

    # Section content
    for section in sections:
        anchor = section.section_name.replace("_", "-")
        parts.append(f'<section id="{anchor}">')
        parts.append(markdown_to_html(section.content))
        parts.append("</section>")

    parts.append("</body></html>")
    return "\n".join(parts)


def _prerender_mermaid(html_content: str) -> str:
    """Run async Mermaid pre-rendering from sync context.

    Handles both cases:
    - No running event loop (CLI): uses asyncio.run()
    - Running event loop (API route via to_thread): uses
      a thread-pool bridge to avoid nested event loop
    """
    try:
        loop = asyncio.get_running_loop()
    except RuntimeError:
        loop = None

    if loop and loop.is_running():
        with concurrent.futures.ThreadPoolExecutor(
            max_workers=1,
        ) as pool:
            return pool.submit(
                asyncio.run,
                prerender_mermaid_blocks(html_content),
            ).result()
    return asyncio.run(
        prerender_mermaid_blocks(html_content)
    )


def export_pdf(
    sections: list[SectionOutput],
    project_id: str,
    output_path: Path | None = None,
) -> bytes:
    """Export sections as a branded PDF document via WeasyPrint.

    This is a synchronous function. When called from an async
    context (e.g. API routes), use ``asyncio.to_thread()`` to
    avoid blocking the event loop.
    """
    from weasyprint import HTML

    html_content = _build_pdf_html(sections, project_id)

    # Pre-render Mermaid code blocks to inline SVG
    html_content = _prerender_mermaid(html_content)

    result = HTML(  # pyright: ignore[reportUnknownMemberType]
        string=html_content, base_url=""
    ).write_pdf()
    if result is None:
        raise RuntimeError("WeasyPrint returned None for PDF render")
    pdf_bytes: bytes = result

    if output_path:
        output_path.write_bytes(pdf_bytes)

    return pdf_bytes


def export_single_section_pdf(
    section: SectionOutput,
) -> bytes:
    """Export a single section as PDF bytes.

    Synchronous — use ``asyncio.to_thread()`` from async callers.
    """
    return export_pdf([section], section.section_name)
